
print('hé hể')
print('Xin chao ADMIN ')

print('Vui long dien cac thong tin sau ')
print('Ten:')

name=input()

print('Ngay sinh: ')
snhat=input()

print('Chon gioi tinh: ')
print('A.Nam / B. Nu')
gt=input()

print('Lop: ')
lop=input()

print('Ma ASC: ')
asc=input()

print('zip qr code: ')
zipqr=input()

f=open('D:\index.html' , 'w') #doi ten tuy theo usser
f.write(' <html lang="en">')
f.write('<head>')
f.write('    <meta charset="UTF-8">')
f.write('    <meta name="viewport" content="width=device-width, initial-scale=1.0">')
f.write('    <title>User</title>')
f.write('</head>')
f.write('<body>')
f.write('   <style>')
f.write('      @import url("https://fonts.googleapis.com/css2?family=Gabarito&family=Josefin+Sans:wght@600&family=Signika:wght@500&display=swap");')
f.write('  </style>')
f.write('  <style>')
f.write('     *{')
f.write('         margin: 0;')
f.write('         padding: 0;')
f.write('     }')
f.write('      body{')
f.write('        background-image: url(https://png.pngtree.com/background/20211215/original/pngtree-green-background-avocado-mosaic-background-picture-image_1457478.jpg);')
f.write('         background-size: cover;}')
   

f.write('     .contanter{')
f.write('        ')
f.write('       ')
f.write('     }')
f.write('   .box{')
f.write('        margin: 0 auto;')
f.write('        text-align: center;')
f.write('    }')
f.write('    img{')
f.write('       height: 150px;')
f.write('    }')
f.write('  li{')
f.write('       font-size: 1.5rem;')
f.write('       font-weight: 1000;')
f.write('       font-family: "Gabarito", sans-serif;')
f.write('font-family: "Josefin Sans", sans-serif;')
f.write('font-family: "Signika", sans-serif;')
f.write('color: rgb(0, 0, 0);')
f.write('     }')
f.write('    .std{')
f.write('       color: red;')
f.write('    }')
f.write('')
f.write('  </style>')
    
        
f.write('  <div class="contanter">')
f.write('     <div class="box">')
f.write('       <img src="https://assets.stickpng.com/images/585e4bf3cb11b227491c339a.png" alt="">')
f.write('       <br> ')
f.write('       <ul>')
f.write('          <br>')
f.write('         <br>')
f.write('         <li>Name:  ' )
f.write(name)
f.write('        </li>')

f.write('       <br>')
f.write(' <li> ')
f.write('Your Birthday:')
f.write(snhat)
f.write('       </li>')
f.write('      <br>')
f.write('      <li>Class: ')
f.write(lop)
f.write(' </li>')
f.write('      <br>')
f.write('      <li> Sex: '  )
f.write(gt)
f.write('              </li>')
f.write('               <br>')
f.write('              <li> ')
f.write('ASC CODE: ')
f.write(asc)
f.write('              </li>')
f.write('            <br>')
f.write('            <li class="std">STUDENT</li>')
f.write('           <br><br><br><br>')
f.write('           <br>')
f.write('      </ul>')
      
f.write('     <img src="./qr_code.png" class="qr" alt="">')
f.write('<br><br><br><br><br><br>')
f.write('          <p style="font-weight: 1000;"> ')
f.write(zipqr)
f.write('<br> </p>')
f.write('  </div>')
f.write('   <br><br>')
f.write('  <p style="text-align: center; font-weight: 900; color: rgb(247, 0, 255);" > @DIEMDANHMMP</p>')
f.write('</body>')
f.write('</html>')
f.close()